const btn1 = document.querySelector('.b1');
const btn2 = document.querySelector('.b2');
const btn3 = document.querySelector('.b3');
const btn4 = document.querySelector('.b4');
const btn5 = document.querySelector('.b5');
const btn6 = document.querySelector('.b6');
const Question1 = () => window.location.href = "../html/rozmowa.html";
const Question2 = () => window.location.href = "../html/rozmowa2.html";
const Question3 = () => window.location.href = "../html/rozmowa3.html";
const Question4 = () => window.location.href = "../html/rozmowa4.html";
btn1.addEventListener('click',Question1);
btn2.addEventListener('click',Question2);
btn3.addEventListener('click',Question3);
btn4.addEventListener('click',Question4);